#!/usr/bin/env bash
#
# Read the YAML frontmatter of every handoff document and answer questions about
# the collection: list them, find one, or point at the newest.
#
# The listing is always derived from the documents themselves, never from a
# hand-maintained list — that way it cannot drift out of sync with reality.
# INDEX.md is a rendered convenience copy, not the source of truth.
#
# Usage:
#   handoff-index.sh                 # rebuild INDEX.md, print all handoffs (newest first)
#   handoff-index.sh --list          # print all handoffs, don't touch INDEX.md
#   handoff-index.sh --find <query>  # print handoffs matching query (id/title/summary/tags)
#   handoff-index.sh --latest        # print the single newest handoff
#   handoff-index.sh --dir <path>    # override the handoff directory
#
# Directory defaults to $HANDOFF_DIR, else ~/.agents/handoffs.
#
# Listing output is one tab-separated record per line:
#   ID <TAB> DATE <TAB> STATUS <TAB> TITLE <TAB> PATH <TAB> SUMMARY
# Exit code 3 means "no handoffs matched"; 0 means at least one did.

set -euo pipefail

DIR="${HANDOFF_DIR:-$HOME/.agents/handoffs}"
MODE="index"
QUERY=""

usage() { sed -n '3,22p' "$0" | sed 's/^# \{0,1\}//'; }

while [ $# -gt 0 ]; do
  case "$1" in
    --dir)    DIR="${2:?--dir needs a path}"; shift 2 ;;
    --find)   MODE="find"; QUERY="${2:?--find needs a query}"; shift 2 ;;
    --latest) MODE="latest"; shift ;;
    --list)   MODE="list"; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "handoff-index: unknown argument '$1'" >&2; exit 2 ;;
  esac
done

mkdir -p "$DIR"

# --- collect ---------------------------------------------------------------
# One record per document: mtime, id, date, status, title, summary, tags, kind, path.
# mtime rides along purely as a tiebreaker for documents written on the same day.

records=""
shopt -s nullglob
for file in "$DIR"/*.md; do
  base="$(basename "$file")"
  [ "$base" = "INDEX.md" ] && continue

  mtime="$(stat -f %m "$file" 2>/dev/null || stat -c %Y "$file" 2>/dev/null || echo 0)"

  record="$(
    awk -v file="$file" -v mtime="$mtime" '
      NR == 1 && $0 !~ /^---[[:space:]]*$/ { exit }      # no frontmatter -> not a handoff
      NR == 1 { in_fm = 1; next }
      in_fm && /^---[[:space:]]*$/ { exit }
      in_fm && match($0, /^[A-Za-z_-]+:/) {
        key = substr($0, 1, RLENGTH - 1)
        val = substr($0, RLENGTH + 1)
        sub(/^[[:space:]]+/, "", val)
        sub(/[[:space:]]+$/, "", val)
        gsub(/^"|"$/, "", val)
        gsub(/\t/, " ", val)
        f[key] = val
      }
      END {
        if (f["id"] == "") exit                          # unusable without an id
        printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n",
          mtime, f["id"], f["date"], f["status"], f["title"], file, f["summary"], f["tags"], f["kind"]
      }
    ' "$file"
  )"

  [ -n "$record" ] && records="${records}${record}"$'\n'
done
shopt -u nullglob

# Newest first: by date descending, then by mtime descending.
records="$(printf '%s' "$records" | grep -v '^$' | sort -t$'\t' -k3,3r -k1,1nr || true)"

if [ -n "$QUERY" ]; then
  # Match case-insensitively against id, title, summary and tags — but not the
  # path, so a query never matches every document via the shared directory name.
  records="$(
    printf '%s\n' "$records" | awk -F'\t' -v q="$(printf '%s' "$QUERY" | tr '[:upper:]' '[:lower:]')" '
      NF { haystack = tolower($2 " " $5 " " $7 " " $8); if (index(haystack, q)) print }
    '
  )"
fi

[ "$MODE" = "latest" ] && records="$(printf '%s\n' "$records" | grep -v '^$' | head -n 1 || true)"

# --- emit ------------------------------------------------------------------

emit_listing() {
  printf '%s\n' "$records" | awk -F'\t' 'NF { printf "%s\t%s\t%s\t%s\t%s\t%s\n", $2, $3, $4, $5, $6, $7 }'
}

if [ "$MODE" = "index" ]; then
  {
    echo "# Handoffs"
    echo
    echo "Generated by \`handoff-index.sh\` — edit the documents, not this file."
    echo "Resume one with \`/handoff-resume <id>\`, or"
    echo
    if [ -z "$records" ]; then
      echo "_No handoff documents yet._"
    else
      printf '%s\n' "$records" | awk -F'\t' 'NF {
        status = ($4 == "" ? "unknown" : $4)
        kind = ($9 == "" ? "" : " — _" $9 "_")
        printf "- **%s** — `%s`%s — %s\n", $2, status, kind, ($5 == "" ? "(untitled)" : $5)
        if ($7 != "") printf "  %s\n", $7
      }'
    fi
  } > "$DIR/INDEX.md"
fi

if [ -z "$records" ]; then
  if [ -n "$QUERY" ]; then
    echo "handoff-index: no handoff matches '$QUERY' in $DIR" >&2
  else
    echo "handoff-index: no handoff documents in $DIR" >&2
  fi
  exit 3
fi

emit_listing
